add_library(usermod_picovector INTERFACE)

set(PNGDEC_DIR "${CMAKE_CURRENT_LIST_DIR}/lib/pngdec")
set(JPEGDEC_DIR "${CMAKE_CURRENT_LIST_DIR}/lib/jpegdec")

find_package(PNGDEC CONFIG REQUIRED)
find_package(JPEGDEC CONFIG REQUIRED)

list(APPEND SOURCES
  # PicoVector C/C++ library (unchanged)
  ${CMAKE_CURRENT_LIST_DIR}/picovector.cpp
  ${CMAKE_CURRENT_LIST_DIR}/shape.cpp
  ${CMAKE_CURRENT_LIST_DIR}/font.cpp
  ${CMAKE_CURRENT_LIST_DIR}/pixel_font.cpp
  ${CMAKE_CURRENT_LIST_DIR}/image.cpp
  ${CMAKE_CURRENT_LIST_DIR}/brush.cpp
  ${CMAKE_CURRENT_LIST_DIR}/color.cpp
  ${CMAKE_CURRENT_LIST_DIR}/primitive.cpp
  ${CMAKE_CURRENT_LIST_DIR}/algorithms/geometry.cpp
  ${CMAKE_CURRENT_LIST_DIR}/algorithms/dda.cpp
  ${CMAKE_CURRENT_LIST_DIR}/brushes/pattern.cpp
  ${CMAKE_CURRENT_LIST_DIR}/brushes/color.cpp
  ${CMAKE_CURRENT_LIST_DIR}/brushes/image.cpp
  ${CMAKE_CURRENT_LIST_DIR}/brushes/gradient.cpp
  ${CMAKE_CURRENT_LIST_DIR}/brushes/pixelate.cpp
  ${CMAKE_CURRENT_LIST_DIR}/brushes/blur.cpp
  ${CMAKE_CURRENT_LIST_DIR}/brushes/brightness.cpp
  ${CMAKE_CURRENT_LIST_DIR}/filters/blur.cpp
  ${CMAKE_CURRENT_LIST_DIR}/filters/dither.cpp
  ${CMAKE_CURRENT_LIST_DIR}/filters/monochrome.cpp
  ${CMAKE_CURRENT_LIST_DIR}/filters/onebit.cpp
  # AUTOGENERATED MicroPython bindings (from the type-annotated DSL in bindings/)
  ${CMAKE_CURRENT_LIST_DIR}/bindings/generated/picovector_bindings.c
  ${CMAKE_CURRENT_LIST_DIR}/bindings/generated/vec2.cpp
  ${CMAKE_CURRENT_LIST_DIR}/bindings/generated/rect.cpp
  ${CMAKE_CURRENT_LIST_DIR}/bindings/generated/mat3.cpp
  ${CMAKE_CURRENT_LIST_DIR}/bindings/generated/color.cpp
  ${CMAKE_CURRENT_LIST_DIR}/bindings/generated/brush.cpp
  ${CMAKE_CURRENT_LIST_DIR}/bindings/generated/shape.cpp
  ${CMAKE_CURRENT_LIST_DIR}/bindings/generated/image.cpp
  ${CMAKE_CURRENT_LIST_DIR}/bindings/generated/font.cpp
  ${CMAKE_CURRENT_LIST_DIR}/bindings/generated/pixel_font.cpp
  ${CMAKE_CURRENT_LIST_DIR}/bindings/generated/algorithm.cpp
  # shared glue + hand-written (native) bodies + companion image decoders
  ${CMAKE_CURRENT_LIST_DIR}/bindings/runtime/pv_support.cpp
  ${CMAKE_CURRENT_LIST_DIR}/bindings/native/font_native.cpp
  ${CMAKE_CURRENT_LIST_DIR}/bindings/native/pixel_font_native.cpp
  ${CMAKE_CURRENT_LIST_DIR}/bindings/native/image_native.cpp
  ${CMAKE_CURRENT_LIST_DIR}/bindings/native/algorithm_native.cpp
  ${CMAKE_CURRENT_LIST_DIR}/bindings/native/image_png.cpp
  ${CMAKE_CURRENT_LIST_DIR}/bindings/native/image_jpeg.cpp
)

target_sources(usermod_picovector INTERFACE
  ${SOURCES}
)

target_include_directories(usermod_picovector INTERFACE
  ${CMAKE_CURRENT_LIST_DIR}
  ${CMAKE_CURRENT_LIST_DIR}/bindings/generated   # types.h
  ${CMAKE_CURRENT_LIST_DIR}/bindings/runtime     # pv_bindings.hpp, pv_objs.hpp
)

target_link_libraries(usermod INTERFACE usermod_picovector pngdec jpegdec)

set_source_files_properties(
  ${SOURCES}
  PROPERTIES COMPILE_FLAGS
  "-Wno-unused-variable"
)

if(DEFINED PICO_BOARD)
  # Build jpegdec for Pico
  target_compile_definitions(jpegdec PRIVATE PICO_BUILD)

  # Build picovector for Pico
  target_compile_definitions(usermod_picovector INTERFACE PICO=1)

  set_source_files_properties(
    ${SOURCES}
    PROPERTIES COMPILE_OPTIONS
    "-O2;-fgcse-after-reload;-floop-interchange;-fpeel-loops;-fpredictive-commoning;-fsplit-paths;-ftree-loop-distribute-patterns;-ftree-loop-distribution;-ftree-vectorize;-ftree-partial-pre;-funswitch-loops"
  )
endif()